name: Rename invoices

on:
  push:
    paths:
      - '**/*.pdf'

jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytesseract PyMuPDF opencv-python unidecode python-dateutil
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtesseract-dev
      - name: Rename invoices
        run: |
          python rename_invoices.py . --inplace
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-rename invoices"
          git push
